### ISSUE TITLE
Custom protocol, Category and DPDK integration

### ISSUE THREAD

**Issue by rashidali-net-sys** [ntop/nDPI#1839]
I am working on the nDPI-4.0 and nDPI-4.4 versions simultaneously. I have initialized the SNI of required protocols and categories as per documentation but didn't see require category names in flow stats (-v 2 arguments).

My changes are as under:
4.0-stable/src/lib/ndpi_content_match.c.inc
{ "acm.org",                          "ACM",      NDPI_PROTOCOL_ACM, NDPI_PROTOCOL_CATEGORY_RESEARCH, NDPI_PROTOCOL_ACCEPTABLE },

4.0-stable/src/include/ndpi_typedefs.h
NDPI_PROTOCOL_CATEGORY_RESEARCH,

4.0-stable/src/include/ndpi_protocol_ids.h
NDPI_PROTOCOL_ACM              = Last_ID+1,

Moreover, I want to integrate DPDK 19 and 21 version applications like l3fwd and l2fwd for testing purposes with both versions. Kindly guide me on how to proceed further as I am getting lot of  library error especially the following.

/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/emmintrin.h:700:1: note: expected ‘__m128i’ but argument is of type ‘int’
 _mm_storeu_si128 (__m128i *__P, __m128i __B)

/usr/local/include/rte_memcpy.h:810:2: error: incompatible type for argument 2 of ‘_mm_storeu_si128’
  MOVEUNALIGNED_LEFT47(dst, src, n, srcofs);

**Comment by IvanNardi** [comment]
> I am working on the nDPI-4.0 and nDPI-4.4 versions simultaneously. I have initialized the SNI of required protocols and categories as per documentation but didn't see require category names in flow stats (-v 2 arguments).
> 

You need to update ` static const char* categories[]` in `ndpi_main.c`

> 
> Moreover, I want to integrate DPDK 19 and 21 version applications like l3fwd and l2fwd for testing purposes with both versions. Kindly guide me on how to proceed further as I am getting lot of library error especially the following.

I have not idea what you are doing with DPDK... `ndpiReder` integration with DPDK <= 19 works fine...
It should be fine to modify `l3fwd` source code (and *keep using* DPDK build system) adding nDPI functionality

**Comment by rashidali-net-sys** [comment]
> You need to update ` static const char* categories[]` in `ndpi_main.c`
> 
Thank for help. Issue resolved
> 
> I have not idea what you are doing with DPDK... `ndpiReder` integration with DPDK <= 19 works fine... It should be fine to modify `l3fwd` source code (and _keep using_ DPDK build system) adding nDPI functionality

I am using DPDK as a fast packet-capturing module from a switch and router interface. Also, guide me on will the new version of DPDK (meson-build) integrated easily with nDPI-4.4 and nDPI-4.0 versions.
Also, I tried to make integration of DPDK-19 version with nDPI-4.0. I get the following mentioned error while doing "make" outside the example  while encountering no issue in doing "make -f Makefile.dpdk".

**Comment by lucaderi** [comment]
Sorry, we're not DPDK experts. We have provided you a DPDK demo application part of nDPI. If you encounter problems and want to contribute, please feel free to send us a pull request.
