### ISSUE TITLE
make error:unknown type name ‘json_object’

### ISSUE THREAD

**Issue by ghost** [ntop/nDPI#414]
a error while making:
......
ndpiReader.c: In function ‘bpf_filter_produce_filter’:
ndpiReader.c:2310:3: error: unknown type name ‘json_object’
   json_object *jObj_bpfFilter = json_object_new_object();
   ^
......
thx

**Comment by YumingMa** [comment]
I met the same error. the error was caused by 7235c9a7.

**Comment by kYroL01** [comment]
Let me know if the error is fixed now

**Comment by ghost** [comment]
nice work,it works:)
